### ISSUE TITLE
Sort records by date on related records widget

### ISSUE THREAD

**Issue by hailyodv** [OpenDevelopmentMekong/wpckan#177]
Hi,
There are errors 
1. The part of library on the vietnamese page still appears english records and otherwise 
2. we want to sort the library records by date (the latest records will display on top)
![untitled](https://cloud.githubusercontent.com/assets/21078816/18778629/66c27c2e-819f-11e6-87fc-016fbe0a64f5.png)

Thank you very much for fixing this

**Comment by acorbi** [comment]
@hailyodv The reason why the dataset titles are appearing in English is because they have not been translated to vietnamese yet. please contact me if you need support on this.

Your second request was already implemented, you can now order posts by date.

![Uploading Screenshot from 2016-10-24 15-03-34.png…]()
