### ISSUE TITLE
Adapt WPCKAN query resources by post category so it works on dataset detail page

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wpckan#218]
This widget shows related datasets by using the post's categories. In case of the dataset detail page, this widget cannot currently be used because the dataset detail page is not a wordpress post and the categories information is not available.

The logic of the widget needs to be adapted so it detects when it is added to a dataset detail page and then uses the dataset's taxonomic terms to query for related content on CKAN.

**Comment by prustar** [comment]
@acorbi -- I was going to suggest that the side bar actually display the search results that were produced so that the user could actually view the detail page and switch to the search results to view additional items as well without having to go back and forth - which is currently not a feature and has been raised by users. 

You could then list the other related results using the widget to generate more general data that could be related.
