### ISSUE TITLE
Filter related datasources by languages

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#72]
The related datasources are displayed on briefing page not filtering by the language. See the screenshot. 
![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/6438110/a0ec5168-c0f8-11e4-9bfa-8b19dcb3a791.jpg)

Improve the functionality of the plugin to support multiple languages. Related datasources can be filtered by languages. It means that in Khmer page, the related dataset will show in khmer dataset.

**Comment by acorbi** [comment]
This could be implemented with https://github.com/OpenDevelopmentMekong/wpckan/issues/73

**Comment by acorbi** [comment]
@WillieShubert @Huyeng @miguelpeixe I have released a new iteration of the plugin https://github.com/OpenDevelopmentMekong/wpckan/releases/tag/wpckan-1.0.0beta4 which includes a functionality to filter queries by extra fields, see **filter_fields** parameter in the documentation.

This feature increases the searching/filtering possibilities in a great way, just wwanted to let you know about it since i believe it can be employed in severals scenarios as the one described in this Issue,

Closing Issue
